[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "duck-stratagem"
version = "0.0.1"
description = "The HELLDIVERS' 'Stratagem Hero' made with python, using pygame"
readme = "README.md"
requires-python = ">=3.8"
authors = [
  { name="Braeden Sy Tan" }
]

dependencies = []

[tool.setuptools.packages.find]
where = ["src"]